export const AUTHORIZE_OAUTH2 = 'AUTHORIZE_OAUTH2'
export const AUTHORIZE_OAUTH2_SUCCESS = 'AUTHORIZE_OAUTH2_SUCCESS'

export const REVOKE_OAUTH2 = 'REVOKE_OAUTH2'
export const REVOKE_OAUTH2_SUCCESS = 'REVOKE_OAUTH2_SUCCESS'

export const GET_APP_SETTINGS = 'GET_APP_SETTINGS'
export const GET_APP_SETTINGS_SUCCESS = 'GET_APP_SETTINGS_SUCCESS'

export const SEND_TEST_MAIL = 'SEND_TEST_MAIL'
export const SEND_TEST_MAIL_SUCCESS = 'SEND_TEST_MAIL_SUCCESS'
