// require('jquery')
require('jquery')
// require('datatables.net-bs')(window, $)
require('jquery.cookie')
require('bootstrap')
require('uiv')
require('bootstrap-select')
// require('bootstrap-slider')
require('@/assets/js/vendor/core/breakpoints')
// require('@/assets/js/vendor/forms/bootstrap-select')
require('jquery.nicescroll')
require('@/assets/js/app/_scrollable')
require('@/assets/js/app/_string-helper')
require('@/assets/js/app/_tree-select')
require('@/assets/js/app/_breakpoints')
require('@/assets/js/app/_sidebar-menu')
require('@/assets/js/app/_dropdown')
require('@/assets/js/app/_sidebar-toggle')
// require('@/assets/js/app/_selectpicker')
// require('@/assets/js/app/_slider')

// require('@/assets/js/app/_skin.js')
// require('@/assets/js/app/_skin_config.js')
// require('grid-a-licious')
// require('@/assets/js/app/_gridalicious.js')

// require('datatables.net')
require('datatables.net-bs')
require('datatables.net-responsive-bs')
require('datatables.net-scroller')
// require('datatables.net-editor-bs')
require('datatables.net-autofill')
require('datatables.net-autofill-bs')
require('datatables.net-buttons-bs')
require('datatables.net-buttons/js/buttons.colVis.js')
require('datatables.net-buttons/js/buttons.print.js')
require('datatables.net-colreorder')
require('datatables.net-fixedcolumns')
require('datatables.net-fixedheader')
require('datatables.net-keytable')
require('datatables.net-rowgroup')
require('datatables.net-rowreorder')
require('datatables.net-select')
require('datatables.net-colreorder')
